//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreIS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookstoreApplicationEntities : DbContext
    {
        public BookstoreApplicationEntities()
            : base("name=BookstoreApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Администраторы> Администраторы { get; set; }
        public virtual DbSet<ЖанрыКниг> ЖанрыКниг { get; set; }
        public virtual DbSet<ЗданиеКнига> ЗданиеКнига { get; set; }
        public virtual DbSet<КнигаОценки> КнигаОценки { get; set; }
        public virtual DbSet<ТаблицаАвторов> ТаблицаАвторов { get; set; }
        public virtual DbSet<ТаблицаЗданий> ТаблицаЗданий { get; set; }
        public virtual DbSet<ТаблицаИздательств> ТаблицаИздательств { get; set; }
        public virtual DbSet<ТаблицаКниг> ТаблицаКниг { get; set; }
        public virtual DbSet<ТаблицаСайтовСОценками> ТаблицаСайтовСОценками { get; set; }
    }
}
