//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТаблицаКниг
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТаблицаКниг()
        {
            this.ЗданиеКнига = new HashSet<ЗданиеКнига>();
            this.КнигаОценки = new HashSet<КнигаОценки>();
            this.ТаблицаАвторов = new HashSet<ТаблицаАвторов>();
            this.ЖанрыКниг = new HashSet<ЖанрыКниг>();
            this.ТаблицаИздательств = new HashSet<ТаблицаИздательств>();
        }
    
        public string ISBN { get; set; }
        public string НазваниеКниги { get; set; }
        public string ГодВыпуска { get; set; }
        public string Переплет { get; set; }
        public Nullable<int> КоличествоСтраниц { get; set; }
        public string ФорматКниги { get; set; }
        public byte[] Обложка { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗданиеКнига> ЗданиеКнига { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<КнигаОценки> КнигаОценки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТаблицаАвторов> ТаблицаАвторов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЖанрыКниг> ЖанрыКниг { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТаблицаИздательств> ТаблицаИздательств { get; set; }
    }
}
