//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТаблицаСайтовСОценками
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТаблицаСайтовСОценками()
        {
            this.КнигаОценки = new HashSet<КнигаОценки>();
        }
    
        public int КодСайта { get; set; }
        public string НазваниеСайта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<КнигаОценки> КнигаОценки { get; set; }
    }
}
