//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТаблицаЗданий
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТаблицаЗданий()
        {
            this.ЗданиеКнига = new HashSet<ЗданиеКнига>();
        }
    
        public int КодЗдания { get; set; }
        public string НазваниеЗдания { get; set; }
        public string Город { get; set; }
        public string Улица { get; set; }
        public string НомерЗдания { get; set; }
        public Nullable<int> Этаж { get; set; }
        public string Назначение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗданиеКнига> ЗданиеКнига { get; set; }
    }
}
