//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТаблицаИздательств
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТаблицаИздательств()
        {
            this.ТаблицаКниг = new HashSet<ТаблицаКниг>();
        }
    
        public int КодИздательства { get; set; }
        public string НазваниеИздательства { get; set; }
        public string Город { get; set; }
        public string Улица { get; set; }
        public string Дом { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТаблицаКниг> ТаблицаКниг { get; set; }
    }
}
